### ISSUE TITLE
Add JavaScript Linting

### ISSUE THREAD

**Issue by smfoote** [smfoote/tornado#33]
Since the code is mostly ES6, we will need to use either JSHint or ESLint plus babel-eslint. This task  includes a lint configuration file (e.g. `.jshintrc`) and a grunt task.

**Comment by smfoote** [comment]
This article might help: https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48

**Comment by prashn64** [comment]
Shot this.

**Comment by smfoote** [comment]
Fixed with #48
