### ISSUE TITLE
SVG and mathML

### ISSUE THREAD

**Issue by jimmyhchan** [smfoote/tornado#38]
Parsing stuff inside of SVG is silly

https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inforeign

https://html.spec.whatwg.org/multipage/syntax.html#adjust-svg-attributes

**Comment by smfoote** [comment]
Can you add some tests to [`html.js`](https://github.com/smfoote/tornado/blob/master/test/acceptance/html.js) that describe what the expected behavior is?

**Comment by jimmyhchan** [comment]
svg accepts a bunch of xml stuff (e.g. CDATA, scripts) not sure what is desirable here.

**Comment by smfoote** [comment]
I don't know if this will fix all of the issues, but #40 gets SVG at least reasonably working. I don't know what would happen when you throw scripts and CDATA into the mix, but I'm hopeful that creating and appending elements will allow the browser to handle the tricky stuff.

**Comment by smfoote** [comment]
I'm going to close this for now. If more issues with Math or SVG come up, we can open more specific issues.
