### ISSUE TITLE
Let the AST visitor do the walking

### ISSUE THREAD

**Issue by jimmyhchan** [smfoote/tornado#67]
Some node handlers (`TORNADO_BODY, HTML_ELEMENT, buildElementAttributes`) currently call `walk`,  `walkAttr` or `step`. Can this logic be moved into the parser instead?

**Comment by jimmyhchan** [comment]
looks like we can use an AST walker that supports `enter` and `leave` (similar to https://github.com/estools/estraverse/wiki/Usage).

**Comment by jimmyhchan** [comment]
some WIP (https://github.com/jimmyhchan/tornado/commit/eff07dadd5d7633742085b8fdc73b49bdffbf91c)  this needs a change in the grammar... just got to figure out where.

**Comment by smfoote** [comment]
Fixed by #66
