### ISSUE TITLE
Support an extensible compiler/parser

### ISSUE THREAD

**Issue by jimmyhchan** [smfoote/tornado#68]
See also #66. In order to simplify the current codebase + allow for future improvements, please support some kind of extension/plugin for the compiler. For example, pegjs/pegjs supports `--plugins`(see https://github.com/pegjs/pegjs/blob/master/lib/peg.js). 

This simplifies our codebase since it allows us to separate our compilation code into passes. Logic can be pulled out (if it doesn't change the AST or require some ordering) into a separate pass (e.g. check the AST).

**Comment by smfoote** [comment]
Fixed by #66. Note, the parser is still not extensible. That will have to wait.
