### ISSUE TITLE
Is it possible to not use tdBody ?

### ISSUE THREAD

**Issue by jimmyhchan** [smfoote/tornado#77]
experiment with not having to keep track of tdBody index

**Comment by jimmyhchan** [comment]
still investigating but it seems like the issue is the instruction `close HTML_ELEMENT` is too big. We are currently treating all it's children (attributes and content) the same and there is logic that the `visitor` needs to introduce, that the instruction generator needs to introduce so that the `generateJS` pass can use.

I plan on: 
-  modifying the AST so that the we introduce HTML_ELEMENT_ATTRIBUTES, TORNADO_BODY_ATTRIBUTES, etc.
- modify the visitor so that HTML_ELEMENT does not walk the sub children (no more knowledge of `tag_info.attributes`
- modify the instructions so that we see closing HTML_ELEMENT_ATTRIBUTES and closing HTML_ELEMENT as two distinct instructions.
- add some data to all `close` instructions so that they know the number of children they have
- modify the stack so that we pop numChildren instead of doing slices

Issues:
- how do we handle badly formed Tornado (e.g. `<h3>hello {?foo}</h3>{/foo}`)? THis currently breaks the parser.

**Comment by smfoote** [comment]
I'm not sure if what you have outlined will obviate the need for `tdBody` (because the opening and closing of HTML is not related to `tdBody`), but you are welcome to give it a try. I do hope it works.

Also, I think the parser should break on malformed Tornado.

**Comment by jimmyhchan** [comment]
it doesn't throw a useful error today.   it breaks unexpectedly.   Ideally we should see `{?foo} is not closed within <h3>`.

This is a related issue since I want to assume `tdBody` will act like an htmlelement node and have children and attributes like an htmlElement node (or the inverse/converse). That is, not only are the related but they are practily the same. So the rules around badly nested html apply to us as well.

**Comment by jimmyhchan** [comment]
fixed in #134
